name: Déploiement

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.5'
      - run: yarn install
      - run: yarn run build
        env:
          BASE_URL: 'https://dev.trouverunefresque.org/'
      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOSTINGER_FTP_SERVER_DEV }}
          username: ${{ secrets.HOSTINGER_FTP_USERNAME_DEV }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD_DEV }}
          local-dir: ./dist/
          server-dir: /
